LABEL_IMAGE = '4X6LABEL'
LABEL_ZPL = '4X6LABELZPL'

SERVICE_PRIORITY = 'PRIORITY'
SERVICE_PRIORITY_EXPRESS = 'PRIORITY EXPRESS'
SERVICE_FIRST_CLASS = 'FIRST CLASS'
SERVICE_PARCEL_SELECT = 'PARCEL SELECT GROUND'
